-
  name: Schedule service health check every 30 minutes
  hosts: localhost
  tasks:
    - name: Ensure log directory exists
      file:
        path: /home/ubuntu/task-ci-cd/configuration_management/log/service_health
        state: directory
        mode: '0755'

    - name: Create cron job for health check
      cron:
        name: "Service Health Check"
        minute: "*/30"
        job: 'bash /home/ubuntu/task-ci-cd/configuration_management/service_health_check.sh'

